object Versions {

    const val androidGradle = "7.0.4"
    const val kotlinGradlePlugin = "1.7.10"
    const val hiltGradlePlugin = "2.44"
    const val legacySupport = "1.0.0"
    const val lifecycleViewModel = "2.5.1"
    const val junit = "4.13.2"
    const val junitTest = "1.1.5"
    const val espresso = "3.5.1"
    const val core = "1.9.0"
    const val appCompat = "1.6.1"
    const val constraintLayout = "2.1.4"
    const val navigationFragment = "2.5.3"
    const val navigationUI = "2.5.3"
    const val lifecycleLiveData = "2.5.1"
    const val coroutines = "1.6.4"
    const val material = "1.8.0"
    const val hilt = "2.44"
    const val hiltCompiler = "2.44"
    const val retrofit = "2.9.0"
    const val retrofitConverterGson = "2.9.0"
    const val room = "2.5.0"
    const val roomCompiler = "2.5.0"
    const val glide = "4.14.2"
    const val glideCompiler = "4.14.2"
    const val timber = "4.7.1"
    const val splashScreen = "1.0.0"
    const val shimmer = "0.5.0"
}